version: '3.3'

volumes:
  pg_data_production:
  static:
  media:

services:

  frontend:
    env_file: .env
    image: aldrpy/foodgram_frontend
    volumes:
      - static:/static
    command: cp -r /app/build/. /static/

  db:
    env_file: .env
    image: postgres:13
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    env_file: .env
    depends_on:
      - db
    image: aldrpy/foodgram_backend
    volumes:
      - media:/media
      - static:/backend_static
      - ../data/:/app/data/

  nginx:
    env_file: .env
    image: aldrpy/foodgram_gateway
    ports:
      - "8000:80"
    volumes:
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend