version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  frontend:
    env_file: .env
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static:/static
    command: cp -r /app/build/. /static/

  db:
    env_file: .env
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=root
    ports:
        - "8080:80"

  backend:
    env_file: .env
    depends_on:
      - db
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - media:/media
      - static:/backend_static
      - ../data/:/app/data/

  nginx:
    env_file: .env
    build: ./
    ports:
      - "8000:80"
    volumes:
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
