# Generated by Django 3.2.16 on 2023-09-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_auto_20230928_1925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientReceipt',
            new_name='IngredientInReceipt',
        ),
    ]
