# Generated by Django 3.2.16 on 2023-09-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_auto_20230929_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-id']},
        ),
    ]
