# Generated by Django 3.2.16 on 2023-09-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_auto_20230929_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipes/images/', verbose_name='Изображение'),
        ),
    ]
