# Generated by Django 3.2.16 on 2023-09-30 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_alter_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinreceipt',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ing_in_rcpt', to='receipts.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientinreceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ing_in_rcpt', to='receipts.receipt', verbose_name='Рецепт'),
        ),
    ]
