# Generated by Django 3.2.16 on 2023-10-04 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0009_rename_ingr_amount_ingredientinreceipt_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ingredientinreceipt',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='ingredientinreceipt',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Количество ингредиента'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время готовки не менее 1 мин'), django.core.validators.MaxValueValidator(32000, 'Время готовки не более 32000 мин')], verbose_name='Время приготовления'),
        ),
    ]
