# Generated by Django 3.2.16 on 2023-09-24 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230923_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_list',
            field=models.ManyToManyField(through='users.Subscription', to=settings.AUTH_USER_MODEL, verbose_name='Подписки пользователя'),
        ),
    ]
