# Generated by Django 3.2.16 on 2023-09-24 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_subscription_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_list',
            field=models.ManyToManyField(related_name='titles', through='users.Subscription', to=settings.AUTH_USER_MODEL, verbose_name='Подписки пользователя'),
        ),
    ]
