# Generated by Django 3.2.16 on 2023-09-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_subscription_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscription_list',
        ),
    ]
