# Generated by Django 3.2.16 on 2023-09-24 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subscription_unique subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribers',
            field=models.ManyToManyField(related_name='authors', through='users.Subscription', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_of_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_of_user', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
    ]
