# Generated by Django 3.2.16 on 2023-09-24 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230925_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='customuser',
            name='fav_authors',
            field=models.ManyToManyField(related_name='subscribers', through='users.Subscription', to=settings.AUTH_USER_MODEL, verbose_name='Подписки на авторов'),
        ),
    ]
